version: "3.9"

services:
backend:
build: ./backend
ports:
\- "5000:5000"
environment:
\- DATABASE\_URI=postgresql://postgres\:postgres\@db:5432/postgres
depends\_on:
\- db

db:
image: postgres:15
restart: always
environment:
POSTGRES\_PASSWORD: postgres
volumes:
\- pgdata:/var/lib/postgresql/data
\- ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
test:
build: ./backend
environment:
\- DATABASE\_URI=postgresql://postgres\:postgres\@db:5432/postgres
depends\_on:
\- db
command: \[ "pytest" ]

volumes:
pgdata:
